// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddOp() {
  return window['go']['Parser']['Parser']['AddOp']();
}

export function AssignStatement() {
  return window['go']['Parser']['Parser']['AssignStatement']();
}

export function ComparisonOp() {
  return window['go']['Parser']['Parser']['ComparisonOp']();
}

export function CurrentToken() {
  return window['go']['Parser']['Parser']['CurrentToken']();
}

export function Exp() {
  return window['go']['Parser']['Parser']['Exp']();
}

export function Factor() {
  return window['go']['Parser']['Parser']['Factor']();
}

export function IfStatement() {
  return window['go']['Parser']['Parser']['IfStatement']();
}

export function Match(arg1) {
  return window['go']['Parser']['Parser']['Match'](arg1);
}

export function MultOp() {
  return window['go']['Parser']['Parser']['MultOp']();
}

export function Parse(arg1) {
  return window['go']['Parser']['Parser']['Parse'](arg1);
}

export function Program() {
  return window['go']['Parser']['Parser']['Program']();
}

export function ReadStatement() {
  return window['go']['Parser']['Parser']['ReadStatement']();
}

export function RepeatStatement() {
  return window['go']['Parser']['Parser']['RepeatStatement']();
}

export function SimpleExp() {
  return window['go']['Parser']['Parser']['SimpleExp']();
}

export function Statement() {
  return window['go']['Parser']['Parser']['Statement']();
}

export function StmtSequence() {
  return window['go']['Parser']['Parser']['StmtSequence']();
}

export function Term() {
  return window['go']['Parser']['Parser']['Term']();
}

export function WriteStatement() {
  return window['go']['Parser']['Parser']['WriteStatement']();
}
