// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {Parser} from '../models';
import {Scanner} from '../models';

export function AddOp():Promise<Parser.Node>;

export function AssignStatement():Promise<Parser.Node>;

export function ComparisonOp():Promise<Parser.Node>;

export function CurrentToken():Promise<Scanner.Token>;

export function Exp():Promise<Parser.Node>;

export function Factor():Promise<Parser.Node>;

export function IfStatement():Promise<Parser.Node>;

export function Match(arg1:string):Promise<Parser.Node>;

export function MultOp():Promise<Parser.Node>;

export function Parse(arg1:string):Promise<Parser.Node>;

export function Program():Promise<Parser.Node>;

export function ReadStatement():Promise<Parser.Node>;

export function RepeatStatement():Promise<Parser.Node>;

export function SimpleExp():Promise<Parser.Node>;

export function Statement():Promise<Parser.Node>;

export function StmtSequence():Promise<Parser.Node>;

export function Term():Promise<Parser.Node>;

export function WriteStatement():Promise<Parser.Node>;
