// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Scan(arg1) {
  return window['go']['Scanner']['ScannerStruct']['Scan'](arg1);
}

export function Transition(arg1, arg2) {
  return window['go']['Scanner']['ScannerStruct']['Transition'](arg1, arg2);
}
