// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {Scanner} from '../models';

export function Scan(arg1:string):Promise<Array<Scanner.Token>>;

export function Transition(arg1:Scanner.Event,arg2:string,arg3:any):Promise<void>;
